# -*- coding: utf-8 -*-
"""UpdatedResult.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aT_Mx1B_ZuLd1mi5oQqbcVkreB9ZdPHY
"""

!pip install -U autogluon.multimodal

from autogluon.multimodal import MultiModalPredictor

df.head()

df = df[['clean_text', 'sentiment']]
df.dropna(inplace=True)

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df['sentiment']
)

from autogluon.multimodal import MultiModalPredictor

predictor = MultiModalPredictor(
    label='sentiment',
    eval_metric='accuracy'
)

predictor.fit(
    train_data=train_df,
    time_limit = 1800  #30 minutes it will run , 30 min = 1800 sec,
    presets='best_quality'
)

result = predictor.evaluate(test_df)

print(result)

sample = pd.DataFrame({
    'clean_text': [
        'Looks cool, but completely impractical for real life problems.'
    ]
})

predictor.predict(sample)

predictor.predict_proba(sample)

import pandas as pd

comments = []

print("Enter comments one by one.")
print("Type DONE when finished.\n")

while True:

    comment = input("Comment: ")

    if comment.upper() == "DONE":
        break

    comments.append(comment)

input_df = pd.DataFrame({
    "clean_text": comments
})

predictions = predictor.predict(input_df)
probabilities = predictor.predict_proba(input_df)

result_df = pd.DataFrame({
    "Comment": comments,
    "Predicted Sentiment": predictions
})

print(result_df)
print("\nProbability Scores:")
print(probabilities)

!pip install streamlit pyngrok -q

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# 
# from autogluon.multimodal import MultiModalPredictor
# from transformers import pipeline
# 
# # ---------------------------
# # Load Models
# # ---------------------------
# 
# @st.cache_resource
# def load_ag():
#     return MultiModalPredictor.load(
#         "/content/AutogluonModels/ag-20260603_150923"
#     )
# 
# @st.cache_resource
# def load_hf():
#     return pipeline(
#         "sentiment-analysis",
#         model="cardiffnlp/twitter-roberta-base-sentiment-latest"
#     )
# 
# ag_model = load_ag()
# hf_model = load_hf()
# 
# # ---------------------------
# # UI
# # ---------------------------
# 
# st.set_page_config(
#     page_title="Instagram Sentiment Analyzer",
#     page_icon="📊",
#     layout="wide"
# )
# 
# st.title("📊 Instagram-Comment-Sentiment Analyzer")
# st.write(
#     "Compare AutoGluon MultiModal predictions with a Transformer model."
# )
# 
# comment = st.text_area(
#     "Enter text",
#     height=150,
#     placeholder="Looks cool, but completely impractical for real life problems."
# )
# 
# # ---------------------------
# # Prediction
# # ---------------------------
# 
# if st.button("Analyze"):
# 
#     if comment.strip():
# 
#         input_df = pd.DataFrame({
#             "clean_text": [comment]
#         })
# 
#         # AutoGluon
#         ag_pred = ag_model.predict(input_df)
#         ag_prob = ag_model.predict_proba(input_df)
# 
#         # Transformer
#         hf_result = hf_model(comment)[0]
# 
#         col1, col2 = st.columns(2)
# 
#         with col1:
# 
#             st.subheader("⚙️ AutoGluon MultiModal")
# 
#             st.success(
#                 f"Prediction: {ag_pred.iloc[0]}"
#             )
# 
#             st.write("Confidence Scores")
# 
#             st.dataframe(
#                 ag_prob,
#                 use_container_width=True
#             )
# 
#         with col2:
# 
#             st.subheader("🤖 Transformer (RoBERTa)")
# 
#             st.success(
#                 f"Label: {hf_result['label']}"
#             )
# 
#             st.metric(
#                 "Confidence",
#                 f"{hf_result['score']:.2%}"
#             )
# 
#         st.divider()
# 
#         st.subheader("📊 Comparison Insight")
# 
#         st.markdown(
#             """
#             - **AutoGluon MultiModal** combines AutoML with deep learning.
#             - **Transformer (RoBERTa)** is highly context-aware and often performs better on sarcasm, contrastive statements, and nuanced language.
#             - Comparing both models helps identify where AutoML and Transformer approaches agree or differ.
#             """
#         )
# 
#     else:
#         st.warning("Enter text first.")

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 > logs.txt 2>&1 &

from pyngrok import ngrok

# Purane tunnels band karo
ngrok.kill()

# Naya tunnel banao
public_url = ngrok.connect(8501)

print("Your Streamlit App URL:")
print(public_url)

!find /content -type f -name "config.yaml"

! pip install autogluon

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv('dataset.csv')

df.head()

df.columns

from autogluon.multimodal import MultiModalPredictor

comment = ["This looks so bad "]

comment_vector = tfidf.transform(comment)

prediction = lr_model.predict(comment_vector)

print(prediction)

